# Generated by Django 4.0.3 on 2022-05-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verify',
            name='otp',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='verify',
            name='token',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
