# Generated by Django 4.0.4 on 2022-06-25 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userd', '0002_jd_application'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='application',
            unique_together={('seek', 'job')},
        ),
    ]
