# Generated by Django 4.0.1 on 2022-03-26 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profilestatus',
            options={'verbose_name_plural': 'Profile Status'},
        ),
    ]
