# Generated by Django 4.0.3 on 2022-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papp', '0002_alter_profilestatus_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='status_content',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
