# Generated by Django 4.0.3 on 2022-04-19 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pikachu',
            name='slug',
            field=models.SlugField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='pikachu',
            name='title',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
