# Generated by Django 4.0.3 on 2022-04-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_pikachu_slug_pikachu_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pikachu',
            name='title',
            field=models.CharField(default='New Title', max_length=20, null=True),
        ),
    ]
