# Generated by Django 4.0.4 on 2022-06-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('seller', 'Seller'), ('customer', 'Customer')], default='customer', max_length=100)),
                ('addon', models.DateField(auto_now=True)),
            ],
        ),
    ]
