# Generated by Django 4.0.4 on 2022-06-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pet',
            field=models.CharField(blank=True, choices=[('dog', 'Dog'), ('cat', 'cat')], max_length=10, null=True),
        ),
    ]
