# Generated by Django 4.0.4 on 2022-06-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='R6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op', models.CharField(max_length=100)),
                ('speed', models.IntegerField()),
                ('side', models.CharField(max_length=100)),
            ],
        ),
    ]
