# Generated by Django 4.0.4 on 2022-06-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_r6'),
    ]

    operations = [
        migrations.AddField(
            model_name='r6',
            name='is_del',
            field=models.BooleanField(null=True),
        ),
    ]
