# Generated by Django 4.0.4 on 2022-06-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_ffproduct_lineitem_order_lineitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(null=True),
        ),
    ]
