# Generated by Django 4.0.3 on 2022-04-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='dad_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='mom_name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
