# Generated by Django 4.0.3 on 2022-05-07 06:38

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('changeapp2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom',
            old_name='user_name',
            new_name='username',
        ),
        migrations.AddField(
            model_name='custom',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
        migrations.AlterField(
            model_name='custom',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E address'),
        ),
    ]
