# Generated by Django 4.0.3 on 2022-04-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_author_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='state',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
