# Generated by Django 4.0.3 on 2022-04-04 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_author_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='near_are',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
