# Generated by Django 4.0.3 on 2022-04-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_author_near_are'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='pincode',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
