# Generated by Django 4.0.3 on 2022-04-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_author_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='pincode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
