# Generated by Django 4.0.1 on 2022-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
